- // MIR for `dedup_multiple_bounds_checks_lengths` before GVN
+ // MIR for `dedup_multiple_bounds_checks_lengths` after GVN
  
  fn dedup_multiple_bounds_checks_lengths(_1: &[i32]) -> [i32; 3] {
      debug x => _1;
      let mut _0: [i32; 3];
      let mut _2: i32;
      let _3: usize;
      let mut _4: bool;
      let mut _5: i32;
      let _6: usize;
      let mut _7: bool;
      let mut _8: i32;
      let _9: usize;
      let mut _10: bool;
  
      bb0: {
          StorageLive(_2);
          StorageLive(_3);
          _3 = const 42_usize;
-         _4 = Lt(copy _3, copy ((_1.1: {ptr metadata for [i32]}).0: usize));
-         assert(move _4, "index out of bounds: the length is {} but the index is {}", copy ((_1.1: {ptr metadata for [i32]}).0: usize), copy _3) -> [success: bb1, unwind unreachable];
+         _4 = Lt(const 42_usize, copy ((_1.1: {ptr metadata for [i32]}).0: usize));
+         assert(move _4, "index out of bounds: the length is {} but the index is {}", copy ((_1.1: {ptr metadata for [i32]}).0: usize), const 42_usize) -> [success: bb1, unwind unreachable];
      }
  
      bb1: {
-         _2 = copy (*_1)[_3];
+         _2 = copy (*_1)[42 of 43];
          StorageLive(_5);
          StorageLive(_6);
          _6 = const 13_usize;
-         _7 = Lt(copy _6, copy ((_1.1: {ptr metadata for [i32]}).0: usize));
-         assert(move _7, "index out of bounds: the length is {} but the index is {}", copy ((_1.1: {ptr metadata for [i32]}).0: usize), copy _6) -> [success: bb2, unwind unreachable];
+         _7 = Lt(const 13_usize, copy ((_1.1: {ptr metadata for [i32]}).0: usize));
+         assert(move _7, "index out of bounds: the length is {} but the index is {}", copy ((_1.1: {ptr metadata for [i32]}).0: usize), const 13_usize) -> [success: bb2, unwind unreachable];
      }
  
      bb2: {
-         _5 = copy (*_1)[_6];
+         _5 = copy (*_1)[13 of 14];
          StorageLive(_8);
          StorageLive(_9);
          _9 = const 7_usize;
-         _10 = Lt(copy _9, copy ((_1.1: {ptr metadata for [i32]}).0: usize));
-         assert(move _10, "index out of bounds: the length is {} but the index is {}", copy ((_1.1: {ptr metadata for [i32]}).0: usize), copy _9) -> [success: bb3, unwind unreachable];
+         _10 = Lt(const 7_usize, copy ((_1.1: {ptr metadata for [i32]}).0: usize));
+         assert(move _10, "index out of bounds: the length is {} but the index is {}", copy ((_1.1: {ptr metadata for [i32]}).0: usize), const 7_usize) -> [success: bb3, unwind unreachable];
      }
  
      bb3: {
-         _8 = copy (*_1)[_9];
+         _8 = copy (*_1)[7 of 8];
          _0 = [move _2, move _5, move _8];
          StorageDead(_8);
          StorageDead(_5);
          StorageDead(_2);
          StorageDead(_9);
          StorageDead(_6);
          StorageDead(_3);
          return;
      }
  }
  
