- // MIR for `array_len` before GVN
+ // MIR for `array_len` after GVN
  
  fn array_len(_1: &mut [i32; 42]) -> usize {
      debug x => _1;
      let mut _0: usize;
      let _2: &[i32];
      let mut _3: &[i32; 42];
      let mut _4: {ptr metadata for [i32]};
      let mut _5: *const [i32];
      scope 1 {
          debug x => _2;
      }
  
      bb0: {
          StorageLive(_2);
          StorageLive(_3);
          _3 = &(*_1);
          _2 = move _3 as &[i32] (PointerCoercion(Unsize, Implicit));
          StorageDead(_3);
          StorageLive(_4);
          StorageLive(_5);
          _5 = &raw const (*_2);
-         _4 = copy (_5.1: {ptr metadata for [i32]});
+         _4 = const {transmute(0x000000000000002a): {ptr metadata for [i32]}};
          StorageDead(_5);
-         _0 = copy (_4.0: usize);
+         _0 = const 42_usize;
          StorageDead(_2);
          StorageDead(_4);
          return;
      }
  }
  
