- // MIR for `make_pointers` before LowerIntrinsics
+ // MIR for `make_pointers` after LowerIntrinsics
  
  fn make_pointers(_1: *const u8, _2: *mut (), _3: usize) -> () {
      debug a => _1;
      debug b => _2;
      debug n => _3;
      let mut _0: ();
      let _4: *const i32;
      let mut _5: *const u8;
      let mut _6: {ptr metadata for i32};
      let mut _7: ();
      let mut _9: *mut ();
      let mut _10: {ptr metadata for u8};
      let mut _11: ();
      let mut _13: *const u8;
      let mut _14: {ptr metadata for [u16]};
      let mut _15: usize;
      let mut _17: *mut ();
      let mut _18: {ptr metadata for [u64]};
      let mut _19: usize;
      scope 1 {
          debug _thin_const => _4;
          let _8: *mut u8;
          scope 2 {
              debug _thin_mut => _8;
              let _12: *const [u16];
              scope 3 {
                  debug _slice_const => _12;
                  let _16: *mut [u64];
                  scope 4 {
                      debug _slice_mut => _16;
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_4);
          StorageLive(_5);
          _5 = copy _1;
          StorageLive(_6);
          StorageLive(_7);
          _7 = ();
          _6 = builtin # ptr_metadata(i32) from (move _7,);
          StorageDead(_7);
-         _4 = aggregate_raw_ptr::<*const i32, *const u8, i32>(move _5, move _6) -> [return: bb1, unwind unreachable];
+         _4 = *const i32 from (move _5, move _6);
+         goto -> bb1;
      }
  
      bb1: {
          StorageDead(_6);
          StorageDead(_5);
          StorageLive(_8);
          StorageLive(_9);
          _9 = copy _2;
          StorageLive(_10);
          StorageLive(_11);
          _11 = ();
          _10 = builtin # ptr_metadata(u8) from (move _11,);
          StorageDead(_11);
-         _8 = aggregate_raw_ptr::<*mut u8, *mut (), u8>(move _9, move _10) -> [return: bb2, unwind unreachable];
+         _8 = *mut u8 from (move _9, move _10);
+         goto -> bb2;
      }
  
      bb2: {
          StorageDead(_10);
          StorageDead(_9);
          StorageLive(_12);
          StorageLive(_13);
          _13 = copy _1;
          StorageLive(_14);
          StorageLive(_15);
          _15 = copy _3;
          _14 = builtin # ptr_metadata([u16]) from (move _15,);
          StorageDead(_15);
-         _12 = aggregate_raw_ptr::<*const [u16], *const u8, [u16]>(move _13, move _14) -> [return: bb3, unwind unreachable];
+         _12 = *const [u16] from (move _13, move _14);
+         goto -> bb3;
      }
  
      bb3: {
          StorageDead(_14);
          StorageDead(_13);
          StorageLive(_16);
          StorageLive(_17);
          _17 = copy _2;
          StorageLive(_18);
          StorageLive(_19);
          _19 = copy _3;
          _18 = builtin # ptr_metadata([u64]) from (move _19,);
          StorageDead(_19);
-         _16 = aggregate_raw_ptr::<*mut [u64], *mut (), [u64]>(move _17, move _18) -> [return: bb4, unwind unreachable];
+         _16 = *mut [u64] from (move _17, move _18);
+         goto -> bb4;
      }
  
      bb4: {
          StorageDead(_18);
          StorageDead(_17);
          _0 = const ();
          StorageDead(_16);
          StorageDead(_12);
          StorageDead(_8);
          StorageDead(_4);
          return;
      }
  }
  
